grc_homepage:
    path:     /
    defaults: { _controller: GrcBundle:List:showDashboard }

grc_fiche_client:
    path:     /client/{id}
    defaults: { _controller: GrcBundle:Ficheclient:ficheclient }
    methods:  [GET, POST]

grc_create_ticket:
    path:     /createticket
    defaults: { _controller: GrcBundle:Createticket:createticket }

grc_create_cat:
    path:     /com/createcat
    defaults: { _controller: GrcBundle:Createcat:createcat }

grc_liste_client:
    path:     /com/listeclient
    defaults: { _controller: GrcBundle:Listeclient:listeclient }

grc_status:
    path:     /com/status/{id}
    defaults: { _controller: GrcBundle:Status:status }
    methods:  [GET, POST]

grc_priority:
    path:     /com/priority/{id}
    defaults: { _controller: GrcBundle:Priority:priority }
    methods:  [GET, POST]

grc_submit_cat:
    path:     /submitcat
    defaults: { _controller: GrcBundle:Createcat:submitcat }

grc_submit_sscat:
    path:     /submitsscat
    defaults: { _controller: GrcBundle:Createcat:submitsscat }

grc_download:
    pattern: /download/{name}
    defaults: { _controller: GrcBundle:Download:download}

ticket:
    path:     /ticket/{id}
    defaults: { _controller: GrcBundle:Ticket:ticket }
    methods:  [GET, POST]

liste:
    path:     /com/liste
    defaults: { _controller: GrcBundle:Alltickets:alltickets}

search:
    path:     /search
    defaults: { _controller: GrcBundle:Search:search}

searchcat:
    path:     /searchcat
    defaults: { _controller: GrcBundle:Search:searchcat}

ajaxsscat:
    path:     /ajaxsscat/
    defaults: { _controller: GrcBundle:Ajaxsscat:ajaxsscat }
    methods:  [GET, POST]

ajaxparamticket:
    path:     /ajaxparamticket/
    defaults: { _controller: GrcBundle:Ajaxparamticket:ajaxparamticket }
    methods:  [GET, POST]

ajaxchart:
    path:     /ajaxchart/
    defaults: { _controller: GrcBundle:Chart:chart }
    methods:  [GET, POST]

ticket_comment:
    path:     /newcom
    defaults: { _controller: GrcBundle:Addcomment:addcomment }