ged_homepage:
    path:     /
    defaults: { _controller: GedBundle:List:showDashboard }
    # defaults: { _controller: GedBundle:Upload:upload }

# ged_upload:
#     path:     /upload
#     defaults: { _controller: GedBundle:Default:upload }