ged_homepage:
    path:     /
    defaults: { _controller: GedBundle:List:showDashboard }

ged_search:
    path:     /search
    defaults: { _controller: GedBundle:Search:search }

ged_ajax_sscat_search:
    path:     /search/souscategorie
    defaults: { _controller: GedBundle:Search:ajaxsscat }
    methods:  [GET, POST]

ged_all:
    path:     /all
    defaults: { _controller: GedBundle:List:all }

ged_parameters_file:
    path:     /parameters/{id}
    defaults: { _controller: GedBundle:Parameters:parameters }

one_file:
    path:     /file/{id}
    defaults: { _controller: GedBundle:File:show }

new_comment:
    path:     /newcom
    defaults: { _controller: GedBundle:File:addComment }

ged_download:
    pattern: /download/{name}
    defaults: { _controller: GedBundle:Download:download}

ged_newgroup:
    path:     /newgroup
    defaults: { _controller:GedBundle:Group:createGroup }

ged_editgroup:
    path:     /editgroup/{id}
    defaults: { _controller:GedBundle:Group:editGroup }

ged_addfiletogroup:
    path:    /addfiletogroup/{idfile}
    defaults: { _controller:GedBundle:File:addToGroup }