ged_homepage:
    path:     /
    defaults: { _controller: GedBundle:List:showDashboard }

ged_all:
    path:     /all
    defaults: { _controller: GedBundle:List:all }

ged_parameters_file:
    path:     /parameters/{id}
    defaults: { _controller: GedBundle:Parameters:parameters }


one_file:
    path:     /file/{id}
    defaults: { _controller: GedBundle:File:show }

new_comment:
    path:     /newcom
    defaults: { _controller: GedBundle:File:addComment }
ged_download:
    pattern: /download/{name}
    defaults: { _controller: GedBundle:Download:download}
